### PR TITLE
Enable travis CI

### PR DESCRIPTION
**Pull request by kevmoo**
Requires environment variables set on Travis
Closes https://github.com/Janamou/firebase3-dart/issues/5

### CODE REVIEW

**Comment by kevmoo** [comment]
@Janamou you'll need to set up travis, set environment variables, etc

Also: you want to make sure you don't build pull requests – someone very sneaky could create a pull request that grabs your firebase private key

**Comment by Janamou** [comment]
Thanks!

**Comment by kevmoo** [comment]
@Janamou let me know if you'd like help setting up travis 😄

**Comment by Janamou** [comment]
@kevmoo works, thanks 👍

**Pull request merged**
