### PR TITLE
Kevmoo tweaks

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by Janamou** [comment]
@kevmoo do we really want this?

The reason why I wrapped every JS object was that I thought that we want to deal with nice Dart types and not with some unknown type of `JSObject`.

Example:

``` dart
var provider = new fb.GoogleAuthProvider();
try {
  fb.UserCredential result = await fb.auth().signInWithPopup(provider);
  print(result.credential.runtimeType);
} catch(e) {
  print(e);
}
```

How it was before:
`print(result.credential.runtimeType); // prints AuthCredential`

How is it now:
`print(result.credential.runtimeType); // prints JSObject`

I was more happier to deal with `AuthCredential` and not with `JSObject`...

**Comment by kevmoo** [comment]
Gotcha. From my perspective, this is a minor concern – and likely something we should fix w/ dart2js.

Less wrapping means smaller code and faster execution. It's also a lot less complexity to deal w/ in the code base.

IMHO 😄

**Comment by Janamou** [comment]
@kevmoo is the code size and code execution performance so bad compared to better developer experience and debugging with meaningful types?

This is question for you and your colleagues. Why can't the js library return type of correct interop-annotated class (for example _the old_ AuthCredentialJsImpl) instead of JSObject? That would make development of interop libraries a lot easier.

Trust me, I am not happy about creating new object for everything/almost every time you call some method but working with JSObject is **hell**.

**Comment by Janamou** [comment]
@kevmoo I know that we have to have some classes "wrapped" because of the need to reimplement Promise -> Future, putting streams etc. But correct runtimeType from annotated classes would be nice :-)

**Comment by kevmoo** [comment]
I dug in a bit. Because closure compiler loves to do crazy things with creating objects, there is effectively no way to figure out the source constructor from the instance.

Of course, from a web context, one can always use `window.console.debug`

I'm going to file an issue to at least let one opt-in to printing some sort of info about vanilla objects.

**Comment by kevmoo** [comment]
@Janamou see https://github.com/dart-lang/sdk/issues/27117

I have strong opinions about this package – because it'll be so popular. 😄 

My concern: while debugging won't be ideal, encouraging best practices will show folks how to mix and match Dart objects and native objects – because when it **does** matter, we could see a big runtime hit with everything be wrapped and unwrapped constantly.

See what I mean?

**Comment by kevmoo** [comment]
@Janamou thanks for fighting back! I really appreciate it. Let me know if you think I'm crazy.

**Comment by Janamou** [comment]
@kevmoo 😀😀😀
Anyway what is your plan for this package (I wrote you e-mail couple days before). I would love to dive into database tests at the moment but I am not sure if you are not working on it 😀 ??

and remove the "unnecessary" wrappers. I created issue for it: #13

**Pull request merged**
